version: '3.8'

services:
  # Entity-based Architecture
  entity-backend:
    build:
      context: ./entity-based-ecommerce/backend
      dockerfile: Dockerfile
    container_name: entity-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-jwt-secret-key-entity
      - PORT=3001
    volumes:
      - entity-backend-data:/app/entity-based-ecommerce/backend/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  entity-frontend:
    build:
      context: ./entity-based-ecommerce/frontend
      dockerfile: Dockerfile
    container_name: entity-frontend
    ports:
      - "4001:4001"
    environment:
      - NUXT_PUBLIC_API_BASE=http://entity-backend:3001
    depends_on:
      entity-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  # Domain-based Architecture
  domain-backend:
    build:
      context: ./domain-based-ecommerce/backend
      dockerfile: Dockerfile
    container_name: domain-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=your-jwt-secret-key-domain
      - PORT=3002
    volumes:
      - domain-backend-data:/app/domain-based-ecommerce/backend/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

  domain-frontend:
    build:
      context: ./domain-based-ecommerce/frontend
      dockerfile: Dockerfile
    container_name: domain-frontend
    ports:
      - "4002:4002"
    environment:
      - NUXT_PUBLIC_API_BASE=http://domain-backend:3002
    depends_on:
      domain-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4002"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - app-network

volumes:
  entity-backend-data:
    driver: local
  domain-backend-data:
    driver: local

networks:
  app-network:
    driver: bridge
